require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SelectedOptionsOfPcsController do

  # This should return the minimal set of attributes required to create a valid
  # SelectedOptionsOfPc. As you add validations to SelectedOptionsOfPc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SelectedOptionsOfPcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all selected_options_of_pcs as @selected_options_of_pcs" do
      selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:selected_options_of_pcs).should eq([selected_options_of_pc])
    end
  end

  describe "GET show" do
    it "assigns the requested selected_options_of_pc as @selected_options_of_pc" do
      selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
      get :show, {:id => selected_options_of_pc.to_param}, valid_session
      assigns(:selected_options_of_pc).should eq(selected_options_of_pc)
    end
  end

  describe "GET new" do
    it "assigns a new selected_options_of_pc as @selected_options_of_pc" do
      get :new, {}, valid_session
      assigns(:selected_options_of_pc).should be_a_new(SelectedOptionsOfPc)
    end
  end

  describe "GET edit" do
    it "assigns the requested selected_options_of_pc as @selected_options_of_pc" do
      selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
      get :edit, {:id => selected_options_of_pc.to_param}, valid_session
      assigns(:selected_options_of_pc).should eq(selected_options_of_pc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SelectedOptionsOfPc" do
        expect {
          post :create, {:selected_options_of_pc => valid_attributes}, valid_session
        }.to change(SelectedOptionsOfPc, :count).by(1)
      end

      it "assigns a newly created selected_options_of_pc as @selected_options_of_pc" do
        post :create, {:selected_options_of_pc => valid_attributes}, valid_session
        assigns(:selected_options_of_pc).should be_a(SelectedOptionsOfPc)
        assigns(:selected_options_of_pc).should be_persisted
      end

      it "redirects to the created selected_options_of_pc" do
        post :create, {:selected_options_of_pc => valid_attributes}, valid_session
        response.should redirect_to(SelectedOptionsOfPc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved selected_options_of_pc as @selected_options_of_pc" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedOptionsOfPc.any_instance.stub(:save).and_return(false)
        post :create, {:selected_options_of_pc => { "user_id" => "invalid value" }}, valid_session
        assigns(:selected_options_of_pc).should be_a_new(SelectedOptionsOfPc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedOptionsOfPc.any_instance.stub(:save).and_return(false)
        post :create, {:selected_options_of_pc => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested selected_options_of_pc" do
        selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
        # Assuming there are no other selected_options_of_pcs in the database, this
        # specifies that the SelectedOptionsOfPc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SelectedOptionsOfPc.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => selected_options_of_pc.to_param, :selected_options_of_pc => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested selected_options_of_pc as @selected_options_of_pc" do
        selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
        put :update, {:id => selected_options_of_pc.to_param, :selected_options_of_pc => valid_attributes}, valid_session
        assigns(:selected_options_of_pc).should eq(selected_options_of_pc)
      end

      it "redirects to the selected_options_of_pc" do
        selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
        put :update, {:id => selected_options_of_pc.to_param, :selected_options_of_pc => valid_attributes}, valid_session
        response.should redirect_to(selected_options_of_pc)
      end
    end

    describe "with invalid params" do
      it "assigns the selected_options_of_pc as @selected_options_of_pc" do
        selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedOptionsOfPc.any_instance.stub(:save).and_return(false)
        put :update, {:id => selected_options_of_pc.to_param, :selected_options_of_pc => { "user_id" => "invalid value" }}, valid_session
        assigns(:selected_options_of_pc).should eq(selected_options_of_pc)
      end

      it "re-renders the 'edit' template" do
        selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectedOptionsOfPc.any_instance.stub(:save).and_return(false)
        put :update, {:id => selected_options_of_pc.to_param, :selected_options_of_pc => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested selected_options_of_pc" do
      selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
      expect {
        delete :destroy, {:id => selected_options_of_pc.to_param}, valid_session
      }.to change(SelectedOptionsOfPc, :count).by(-1)
    end

    it "redirects to the selected_options_of_pcs list" do
      selected_options_of_pc = SelectedOptionsOfPc.create! valid_attributes
      delete :destroy, {:id => selected_options_of_pc.to_param}, valid_session
      response.should redirect_to(selected_options_of_pcs_url)
    end
  end

end
